-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, G.REPLY_ID, G.WRITER_ID, G.CONTENTS, DATE_FORMAT(G.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_REPLY AS G
ON B.BOARD_ID = G.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY G.CREATED_DATE ASC, B.TITLE ASC